Slx\Domain\Entity\User\User:
  type: entity
  repositoryClass: Slx\Infrastructure\Persistence\Doctrine\Repository\User\UserDoctrineRepository
  table: user
  options:
    charset: utf8
    collate: utf8_general_ci
  embedded:
    password:
      class: Slx\Domain\ValueObject\Password\Password
      columnPrefix: false
    email:
      class: Slx\Domain\ValueObject\Email\Email
      columnPrefix: false
    uid:
      class: Slx\Domain\Entity\User\UserId
      columnPrefix: false
  fields:
    username:
      column: userName
      type: string
      nullable: false
    createdOn:
      type: datetime
      nullable: false
    updatedOn:
      type: datetime
      nullable: false
